FROM almalinux:9
ADD https://raw.githubusercontent.com/daws-78s/notes/main/session-01.txt /tmp/session-01.txt
# it is copying the files from source to destination. 
# Here session-1.txt will be copied from URL to /tmp of image
ADD sample-1.tar /tmp/
## it will extract the .tar file and place the extracted file in /tmp
CMD [ "sleep", "60" ]
